"""add client organizations and contacts tables

Revision ID: 0d9ad76f670b
Revises: 20251102_0000
Create Date: 2025-11-11 01:03:51.688012+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9ad76f670b'
down_revision: Union[str, None] = '20251102_0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False, comment='対応するOrganizationのID（1:1関係）'),
    sa.Column('industry', sa.String(length=255), nullable=True, comment='業種'),
    sa.Column('employee_count', sa.Integer(), nullable=True, comment='従業員数'),
    sa.Column('annual_revenue', sa.BigInteger(), nullable=True, comment='年商（円）'),
    sa.Column('established_year', sa.Integer(), nullable=True, comment='設立年'),
    sa.Column('website', sa.String(length=500), nullable=True, comment='Webサイト'),
    sa.Column('sales_person', sa.String(length=255), nullable=True, comment='担当営業'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_organizations_organization_id'), 'client_organizations', ['organization_id'], unique=True)
    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_organization_id', sa.Integer(), nullable=False, comment='顧客組織ID'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='氏名'),
    sa.Column('department', sa.String(length=255), nullable=True, comment='部署'),
    sa.Column('position', sa.String(length=255), nullable=True, comment='役職'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='メールアドレス'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='電話番号'),
    sa.Column('mobile', sa.String(length=50), nullable=True, comment='携帯電話番号'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='主担当フラグ'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_organization_id'], ['client_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contacts_client_organization_id'), 'client_contacts', ['client_organization_id'], unique=False)
    op.drop_index(op.f('ix_organizations_parent_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_parent_organization_id'), 'organizations', ['parent_organization_id'], unique=False)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_organizations_parent_organization_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_parent_id'), 'organizations', ['parent_organization_id'], unique=False)
    op.drop_index(op.f('ix_client_contacts_client_organization_id'), table_name='client_contacts')
    op.drop_table('client_contacts')
    op.drop_index(op.f('ix_client_organizations_organization_id'), table_name='client_organizations')
    op.drop_table('client_organizations')
    # ### end Alembic commands ###
